//! Raw FFI bindings to NVIDIA TensorRT C API.
//!
//! Generated by bindgen from `NvInfer.h`. This crate provides the
//! unsafe foundation that `nordocr-trt` builds safe wrappers on top of.
//!
//! # Safety
//! All functions in this module are unsafe FFI calls. Use `nordocr-trt`
//! for safe Rust wrappers.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

// Include the bindgen-generated bindings.
// At build time on a machine with TensorRT installed, this expands to
// the actual generated FFI types. For development without TensorRT,
// we provide stub types below.
#[cfg(feature = "generated")]
include!(concat!(env!("OUT_DIR"), "/trt_bindings.rs"));

// Stub types for development/CI without TensorRT headers.
// These match the TensorRT 10.x C API signatures we use.
#[cfg(not(feature = "generated"))]
pub mod stubs {
    use std::os::raw::{c_char, c_int, c_void};

    // Opaque handle types mirroring TensorRT C API.
    pub type NvInferRuntime = c_void;
    pub type NvInferEngine = c_void;
    pub type NvInferExecutionContext = c_void;
    pub type NvInferBuilder = c_void;
    pub type NvInferNetworkDefinition = c_void;
    pub type NvInferBuilderConfig = c_void;
    pub type NvInferHostMemory = c_void;
    pub type NvInferParser = c_void;
    pub type NvInferLogger = c_void;

    /// TensorRT data types.
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum NvInferDataType {
        Float = 0,
        Half = 1,
        Int8 = 2,
        Int32 = 3,
        Bool = 4,
        Uint8 = 5,
        Fp8E4M3 = 6,
        Bf16 = 7,
        Int64 = 8,
        Int4 = 9,
        Fp4 = 10,
    }

    /// TensorRT tensor I/O mode.
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum NvInferTensorIOMode {
        None = 0,
        Input = 1,
        Output = 2,
    }

    /// Dimension descriptor.
    #[repr(C)]
    #[derive(Debug, Clone, Copy)]
    pub struct NvInferDims {
        pub nb_dims: c_int,
        pub d: [i64; 8],
    }

    // Extern stubs — these will link to real TensorRT at runtime.
    extern "C" {
        pub fn createInferRuntime(logger: *mut NvInferLogger) -> *mut NvInferRuntime;
        pub fn createInferBuilder(logger: *mut NvInferLogger) -> *mut NvInferBuilder;
    }
}

#[cfg(not(feature = "generated"))]
pub use stubs::*;
